### ISSUE TITLE
Add tests for `.asf`, `.ogm`, `.ogx`, and `.mpc` file types

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/file-type#240]
https://github.com/sindresorhus/file-type/blob/a2692b3471030433f69c11e406456b32f3f49af5/test.js#L12-L17

* [x] `.asf` detection is not working: #290, failing fixture: PR #291
* [x] `ogm`, fixture added in PR #326
* [x] `ogx`, **artificial** fixture added in PR #327
* [x] `mpc`,  2 fixtures added in #176

**Comment by Borewit** [comment]
`.asf` detection is not working: #290
