### ISSUE TITLE
Consider adding `opendocument` and `officedocument` templates mime ?

### ISSUE THREAD

**Issue by sly7-7** [sindresorhus/file-type#709]
### Description

Hello, at this time, it seems templates from ms office and openoffice/libreoffice templates are considered either `application/zip` or at best as there document counter parts. So I was wondering if it would be possible to better analyze these files. For example, using [mime](https://www.npmjs.com/package/mime), it detects these mime types for the following extensions:

- [ ] `ots: application/vnd.oasis.opendocument.spreadsheet-template` (application/zip for file-type) #718
- [ ] `odg: application/vnd.oasis.opendocument.graphics` (application/zip for file-type) #718
- [ ] `otg: application/vnd.oasis.opendocument.graphics-template` (application/zip) #718
- [ ] `otp: application/vnd.oasis.opendocument.presentation-template`(application/zip for file-type) #718
- [ ] `ott: application/vnd.oasis.opendocument.text-template` (application/zip for file-type) #718

- [x] `xltx: application/vnd.openxmlformats-officedocument.spreadsheetml.template` (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for file-type) #712 
- [x] `xltm: application/vnd.ms-excel.template.macroenabled.12` (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet for file-type) #714
- [x] `potx: application/vnd.openxmlformats-officedocument.presentationml.template` (application/vnd.openxmlformats-officedocument.presentationml.presentation for file-type) #710 
- [x] `dotx: application/vnd.openxmlformats-officedocument.wordprocessingml.template` (application/vnd.openxmlformats-officedocument.wordprocessingml.document for file-type) #713 

I don't know much about mime types or file signatures, so I don't know they are good candidates, neither how to do the detections.

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by sly7-7** [comment]
🤔 Reading at the source code, maybe the only thing is to add some mime check here: https://github.com/sindresorhus/file-type/blob/7e72bbccd317efc5d5aed55fdd3af72d3857c781/core.js#L30
 
I think that's worth a try.

**Comment by Borewit** [comment]
> I don't know much about mime types or file signatures, so I don't know they are good candidates, neither how to do the detections.

This is the formal MIME-type registration: https://www.iana.org/assignments/media-types/media-types.xhtml 

Many MIME-types which are in use, do unfortunately lack a formal registration at IANA. If that registration is missing, we can base it on the original specification, an RFC, Wikipedia, or any other reference which suggests what the best MIME-type is. 

It is required to document where you get it from, for traceability. If someone, has a better suggestion, we can easily trace where the existing type came from, and which one is the best to use.

**Comment by sly7-7** [comment]
Thank you, I was answering in the closed PR.
I've made small searches and found [mimetype.io](https://mimetype.io/all-types) and then also found https://www.iana.org/assignments/media-types/media-types.xhtml#application you just mentioned. 
So for the further PRs, I will document/link to these sources in the description (like you did when editing #710).
Also I saw you prefer "Partially resolves" rather than "Related", so I will reference this "meta" issue as you did. (I intentionally used related instead of resolves because I didn't want this issue to be closed on each merge)

**Comment by Borewit** [comment]
Given to you follow the same pattern with previous related PRs, I have no problem if you combine the remaining templates in a combined PR, do you agree @sindresorhus ?

**Comment by sly7-7** [comment]
I'm on vacation, I will do that on Monday if @sindresorhus is ok with that

**Comment by sindresorhus** [comment]
👍

**Comment by sly7-7** [comment]
@Borewit @sindresorhus #718 is ready for review :)
